# System of Linear equations

Iterative techniques to find solutions of `AX = b`

## Jacobi method

In [1]:
import numpy as np

def jacobi(dim, A, B, tol, n):
    """
    Arguments
    ---------
    dim: int
        Dimension of square matrix `A`
    A: 2D np.array
        Coefficient matrix
    B: np.array
        Constant matrix
    tol: float
        tolerance
    n: int
        maximum number of iterations
    """
    X0 = np.array(dim*[np.inf])
    X1 = np.array(dim*[0.]) # Initial vector

    iterations = 0
    while np.max(abs(X0 - X1)) > tol and iterations < n:
        X0 = X1
        X1 = np.array(dim*[0.])

        for i in range(dim):
            for j in range(dim):
                if j != i:
                    X1[i] += (-A[i][j]*X0[j])
            X1[i] += B[i]
            X1[i] /= A[i][i]
        
        print(X1)
        iterations += 1

    print("iterations:", iterations)
    
    return X1

In [2]:
import numpy as np

dim = 3
A = np.array([
    [15, 3, -2],
    [2, 10, 1],
    [1, -2, 8]
    ], dtype=float)
B = np.array([85, 51, 5], dtype=float)
tol = 1e-5
n = 100

jacobi(dim, A, B, tol, n)

[5.66666667 5.1        0.625     ]
[4.73       3.90416667 1.19166667]
[5.04472222 4.03483333 1.00979167]
[4.99433889 3.99007639 1.00311806]
[5.00240046 4.00082042 0.99822674]
[4.99959948 3.99969723 0.99990505]
[5.00004789 4.0000896  0.99997437]
[4.99997866 3.99999298 1.00001641]
[5.00000359 4.00000263 1.00000091]
[4.9999996  3.99999919 1.00000021]
iterations: 10


array([4.9999996 , 3.99999919, 1.00000021])

## Gauss-Seidel method

In [3]:
import numpy as np

def gauss_seidel(dim, A, B, tol, n):
    """
    Arguments
    ---------
    dim: int
        Dimension of square matrix `A`
    A: 2D np.array
        Coefficient matrix
    B: np.array
        Constant matrix
    tol: float
        tolerance
    n: int
        maximum number of iterations
    """
    X0 = np.array(dim*[np.inf])
    X1 = np.array(dim*[0.]) # Initial vector

    iterations = 0
    while np.max(abs(X0 - X1)) > tol and iterations < n:
        X0 = X1
        X1 = np.array(dim*[0.])

        for i in range(dim):
            for j in range(i):
                X1[i] += (-A[i][j]*X1[j])
            for j in range(i+1, dim):
                X1[i] += (-A[i][j]*X0[j])
            
            X1[i] += B[i]
            X1[i] /= A[i][i]
        
        print(X1)
        iterations += 1

    print("iterations:", iterations)
    
    return X1

In [4]:
import numpy as np

dim = 3
A = np.array([
    [8, 2, -2],
    [1, -8, 3],
    [2, 1, 9]
    ], dtype=float)
B = np.array([8, -4, 12], dtype=float)
tol = 1e-5
n = 100

gauss_seidel(dim, A, B, tol, n)

[1.         0.625      1.04166667]
[1.10416667 1.02864583 0.97366898]
[0.98625579 0.98840784 1.00434229]
[1.00398361 1.00212631 0.9988785 ]
[0.99918805 0.99947794 1.00023844]
[1.00019012 1.00011318 0.99994517]
[0.999958   0.99997419 1.0000122 ]
[1.0000095  1.00000576 0.99999725]
[0.99999787 0.9999987  1.00000062]
[1.00000048 1.00000029 0.99999986]
iterations: 10


array([1.00000048, 1.00000029, 0.99999986])

## SOR (Succesive Over Reduction) method

In [7]:
import numpy as np

def SOR(dim, A, B, ω, tol, n):
    """
    Arguments
    ---------
    dim: int
        Dimension of square matrix `A`
    A: 2D np.array
        Coefficient matrix
    B: np.array
        Constant matrix
    ω: float
        Weigth to residual part of Gauss-Siedel method
    tol: float
        tolerance
    n: int
        maximum number of iterations
    """
    X0 = np.array(dim*[np.inf])
    X1 = np.array(dim*[0.]) # Initial vector

    iterations = 0
    while np.max(abs(X0 - X1)) > tol and iterations < n:
        X0 = X1
        X1 = np.array(dim*[0.])

        for i in range(dim):
            for j in range(i):
                X1[i] += (-A[i][j]*X1[j])
            for j in range(i+1, dim):
                X1[i] += (-A[i][j]*X0[j])
            X1[i] += B[i]
            X1[i] /= A[i][i]

            X1[i] *= ω
            X1[i] += (1-ω)*X0[i]
        
        print(X1)
        iterations += 1

    print("iterations:", iterations)
    
    return X1

In [9]:
import numpy as np

dim = 5
A = np.array([
    [4, 1, 1, 0, 1],
    [-1, -3, 1 ,1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
    ], dtype=float)
B = np.array([6, 6, 6, 6, 6], dtype=float)
ω = 1.1
tol = 1e-5
n = 100

SOR(dim, A, B, ω, tol, n)

[ 1.65       -2.805       1.2111      1.6654275   3.06780994]
[ 1.07967477 -1.260654    2.04248922  1.9953725   2.0495358 ]
[ 0.76340549 -0.87330065  1.86185863  1.9322527   1.90600341]
[ 0.77765507 -1.00663597  1.85752216  1.90462358  2.00009655]
[ 0.78821424 -1.00889485  1.86842882  1.9126684   1.99271663]
[ 0.78680966 -1.00120508  1.86641069  1.91303736  1.9885688 ]
[ 0.78653107 -1.0024766   1.86618347  1.9125117   1.98976499]
[ 0.78664213 -1.00266623  1.86634656  1.91258751  1.98977367]
[ 0.78663594 -1.0025574   1.86632762  1.91260294  1.98970349]
[ 0.78663114 -1.00256781  1.86632187  1.91259564  1.98971666]
[ 0.78663244 -1.00257203  1.86632409  1.91259617  1.98971813]
iterations: 11


array([ 0.78663244, -1.00257203,  1.86632409,  1.91259617,  1.98971813])

# System of non-linear equations

Atleast one equation is non-linear.

## Newton-Raphson method

In [ ]:
import numpy as np

def newton_raphson(F, J, X, tol, n):
    """
    Arguments
    ---------
    F: function
        Function returning vector of functions
    J: function returning a matrix
        Function returning Jacobian matrix
    X: np.array
        Initial approximation vector
    tol: float
        tolerance
    n: int
        maximum number of iterations
    """
    E = np.array(np.inf) # Error vector

    iterations = 0
    while np.max(abs(E)) > tol and iterations < n:
        E = -np.dot(np.linalg.inv(J(X)), F(X))
        X = X + E
        iterations += 1
        print(X)

    print("iterations:", iterations)

    return X

In [ ]:
import numpy as np
from math import inf

f = lambda x, y: x**2 + x*y + y**2 - 7
g = lambda x, y: x**3 + y**3 - 9

F = lambda X: np.array([f(*X), g(*X)])

fx = lambda x, y: 2*x + y
fy = lambda x, y: x + 2*y
gx = lambda x, y: 3*x**2
gy = lambda x, y: 3*y**2

J = lambda X: np.array([
    [fx(*X), fy(*X)],
    [gx(*X), gy(*X)]
])

X = np.array([1.5, 0.5])
tol = 1e-6
n = inf

newton_raphson(F, J, X, tol, n)

In [ ]:
# For 3 variables, x,y and z

import numpy as np
from math import inf, sin, cos

f = lambda x, y, z: 10*x + sin(x+y) - 1
g = lambda x, y, z: 8*y - cos(z-y)**2 - 1
h = lambda x, y, z: 12*z + sin(z) - 1

F = lambda X: np.array([f(*X), g(*X), h(*X)])

fx = lambda x, y, z: 10 + cos(x+y)
fy = lambda x, y, z: cos(x+y)
fz = lambda x, y, z: 0
gx = lambda x, y, z: 0
gy = lambda x, y, z: 8 - 2*cos(z-y)*sin(z-y)
gz = lambda x, y, z: 2*cos(z-y)*sin(z-y)
hx = lambda x, y, z: 0
hy = lambda x, y, z: 0
hz = lambda x, y, z: 12 + cos(z)

J = lambda X: np.array([
    [fx(*X), fy(*X), fz(*X)],
    [gx(*X), gy(*X), gz(*X)],
    [hx(*X), hy(*X), hz(*X)]
])

X = np.array([1/10, 1/4, 1/12])
tol = 1e-6
n = inf

newton_raphson(F, J, X, tol, n)

In [ ]:
# Using X instead of x, y, z, ... for math function lambdas
# Use this as input method if there are 4 or more parameters

import numpy as np
from math import inf

f = lambda X: X[0]**2 + X[0]*X[1] + X[1]**2 - 7
g = lambda X: X[0]**3 + X[1]**3 - 9

F = lambda X: np.array([f(X), g(X)])

fx = lambda X: 2*X[0] + X[1]
fy = lambda X: X[0] + 2*X[1]
gx = lambda X: 3*X[0]**2
gy = lambda X: 3*X[1]**2

J = lambda X: np.array([
    [fx(X), fy(X)],
    [gx(X), gy(X)]
])

X = np.array([1.5, 0.5])
tol = 1e-6
n = inf

newton_raphson(F, J, X, tol, n)